---
- name: Get OS type
  debug:
    var: ansible_facts.distribution

- name: Create dir
  file:
    path:  '{{ vagrant_home }}'
    state: directory
#    owner: flink
#    group: flink
#    mode: '0755'


- name: Download vagrant
  get_url:
    url: 'https://releases.hashicorp.com/vagrant/2.2.15/vagrant_2.2.15_linux_amd64.zip'
    dest: /tmp

- name: Unarchive 
  unarchive:
    src: /tmp/vagrant_2.2.15_linux_amd64.zip
    dest: '{{ vagrant_home }}'


- name: add to path
  lineinfile:
    dest: '~/.profile'
    state: present
    #line: "export PATH=$PATH:/opt/packer/"
    backrefs: true
    regexp: 'PATH=(["]*)((?!.*?{{ vagrant_home }}).*?)(["]*)$'
    line: 'PATH=\1\2:{{ vagrant_home }}\3'

